name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan ${REMOTE_HOST} > ~/.ssh/known_hosts
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 400 ssh_key
          ssh -i ssh_key ${REMOTE_USER}@${REMOTE_HOST} 'cd Walter-Bot/ && git stash && eval "$(ssh-agent -s)" && git pull --ff-only origin main && ./deploy.sh'
