name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          set -e
          ssh -i "${SSH_PRIVATE_KEY}" "${REMOTE_USER}@${REMOTE_HOST}" && cd ~/Walter-bot/ && pupdate && npm i && node deploy-commands.js && pm2 restart index.js
